const recipes = [
  {
    id: 1,
    title: "Spaghetti Carbonara",
    ingredients: [
      "spaghetti",
      "eggs",
      "parmesan cheese",
      "bacon",
      "black pepper",
      "salt",
    ],
    instructions:
      "Cook pasta. Mix eggs and cheese. Fry bacon. Combine everything and serve with pepper.",
    image: "https://example.com/images/carbonara.jpg",
    tags: ["italian", "pasta", "quick"],
    author: "Gonçalo Amaro",
  },
  {
    id: 2,
    title: "Chicken Tikka Masala",
    ingredients: [
      "chicken",
      "yogurt",
      "tomato puree",
      "onion",
      "garam masala",
      "cream",
    ],
    instructions:
      "Marinate chicken. Grill or fry. Cook sauce separately and combine with chicken. Simmer and serve.",
    image: "https://example.com/images/tikka.jpg",
    tags: ["indian", "spicy", "dinner"],
    author: "Aisha Khan",
  },
  {
    id: 3,
    title: "Avocado Toast",
    ingredients: [
      "bread",
      "avocado",
      "lemon juice",
      "salt",
      "chili flakes",
      "eggs",
    ],
    instructions:
      "Toast bread. Mash avocado with lemon, salt. Spread on toast and sprinkle chili flakes. Fry an egg and lay it on the top.",
    image: "https://example.com/images/avocado-toast.jpg",
    tags: ["vegan", "breakfast", "quick"],
    author: "Liam Smith",
  },
  {
    id: 4,
    title: "Beef Tacos",
    ingredients: [
      "ground beef",
      "taco shells",
      "lettuce",
      "cheddar",
      "salsa",
      "sour cream",
    ],
    instructions:
      "Cook beef with spices. Fill taco shells and top with lettuce, cheese, salsa, and sour cream.",
    image: "https://example.com/images/tacos.jpg",
    tags: ["mexican", "dinner", "easy"],
    author: "Sofia Martinez",
  },
  {
    id: 5,
    title: "Greek Salad",
    ingredients: [
      "cucumber",
      "tomatoes",
      "red onion",
      "feta cheese",
      "olives",
      "olive oil",
      "oregano",
    ],
    instructions:
      "Chop vegetables. Mix with feta and olives. Drizzle olive oil and sprinkle oregano.",
    image: "https://example.com/images/greek-salad.jpg",
    tags: ["salad", "healthy", "vegetarian"],
    author: "Nikos Papadopoulos",
  },
  {
    id: 6,
    title: "Pad Thai",
    ingredients: [
      "rice noodles",
      "shrimp",
      "tofu",
      "bean sprouts",
      "egg",
      "peanuts",
      "tamarind paste",
      "lime",
    ],
    instructions:
      "Soak noodles. Stir-fry shrimp and tofu. Add egg, then noodles and sauce. Top with sprouts and peanuts.",
    image: "https://example.com/images/pad-thai.jpg",
    tags: ["thai", "noodles", "dinner"],
    author: "Somchai Kittisak",
  },
  {
    id: 7,
    title: "French Onion Soup",
    ingredients: [
      "onions",
      "beef broth",
      "baguette",
      "gruyere cheese",
      "butter",
      "thyme",
    ],
    instructions:
      "Caramelize onions, add broth and thyme, simmer. Serve with toasted baguette and melted cheese.",
    image: "https://example.com/images/french-onion-soup.jpg",
    tags: ["french", "soup", "comfort food"],
    author: "Marie Dubois",
  },
  {
    id: 8,
    title: "Vegetable Stir Fry",
    ingredients: [
      "broccoli",
      "carrots",
      "bell pepper",
      "soy sauce",
      "ginger",
      "garlic",
      "sesame oil",
    ],
    instructions:
      "Stir-fry vegetables with ginger and garlic. Add soy sauce and sesame oil. Serve hot.",
    image: "https://example.com/images/veg-stir-fry.jpg",
    tags: ["vegan", "asian", "quick"],
    author: "Wei Zhang",
  },
  {
    id: 9,
    title: "Fish Tacos",
    ingredients: [
      "white fish",
      "taco shells",
      "cabbage",
      "lime",
      "cilantro",
      "sour cream",
    ],
    instructions:
      "Grill fish. Fill shells with fish, cabbage, and sauce. Top with lime and cilantro.",
    image: "https://example.com/images/fish-tacos.jpg",
    tags: ["mexican", "seafood", "easy"],
    author: "Carlos Ramirez",
  },
  {
    id: 10,
    title: "Pancakes",
    ingredients: ["flour", "milk", "eggs", "baking powder", "sugar", "butter"],
    instructions:
      "Mix ingredients. Cook on griddle until golden. Serve with butter and syrup.",
    image: "https://example.com/images/pancakes.jpg",
    tags: ["breakfast", "sweet", "quick"],
    author: "Emma Johnson",
  },
  {
    id: 11,
    title: "Shakshuka",
    ingredients: [
      "eggs",
      "tomatoes",
      "onion",
      "bell pepper",
      "cumin",
      "paprika",
    ],
    instructions:
      "Cook vegetables with spices, add tomatoes, simmer. Make wells, add eggs, cook until set.",
    image: "https://example.com/images/shakshuka.jpg",
    tags: ["middle eastern", "breakfast", "vegetarian"],
    author: "Yasmin Elbaz",
  },
  {
    id: 12,
    title: "Classic Cheeseburger",
    ingredients: [
      "ground beef",
      "cheddar cheese",
      "lettuce",
      "tomato",
      "bun",
      "onion",
      "ketchup",
    ],
    instructions: "Grill patties. Add cheese, assemble burgers with toppings.",
    image: "https://example.com/images/cheeseburger.jpg",
    tags: ["american", "grill", "dinner"],
    author: "James Miller",
  },
  {
    id: 13,
    title: "Caprese Salad",
    ingredients: [
      "mozzarella",
      "tomatoes",
      "basil",
      "olive oil",
      "balsamic glaze",
    ],
    instructions:
      "Slice mozzarella and tomatoes. Layer with basil. Drizzle oil and glaze.",
    image: "https://example.com/images/caprese.jpg",
    tags: ["italian", "salad", "vegetarian"],
    author: "Elena Rossi",
  },
  {
    id: 14,
    title: "Sushi Rolls",
    ingredients: [
      "sushi rice",
      "nori",
      "salmon",
      "cucumber",
      "avocado",
      "soy sauce",
    ],
    instructions:
      "Lay rice on nori, add fillings, roll tightly, slice. Serve with soy sauce.",
    image: "https://example.com/images/sushi.jpg",
    tags: ["japanese", "seafood", "snack"],
    author: "Hiro Tanaka",
  },
  {
    id: 15,
    title: "Falafel Wrap",
    ingredients: [
      "falafel",
      "pita bread",
      "lettuce",
      "tomato",
      "cucumber",
      "tahini",
    ],
    instructions: "Fill pita with falafel and veggies. Drizzle tahini.",
    image: "https://example.com/images/falafel-wrap.jpg",
    tags: ["middle eastern", "vegan", "street food"],
    author: "Layla Hassan",
  },
  {
    id: 16,
    title: "Egg Fried Rice",
    ingredients: ["rice", "egg", "peas", "carrot", "soy sauce", "green onion"],
    instructions: "Fry veggies and rice, add egg, stir, season with soy sauce.",
    image: "https://example.com/images/egg-fried-rice.jpg",
    tags: ["chinese", "quick", "comfort food"],
    author: "Jun Li",
  },
  {
    id: 17,
    title: "Pumpkin Soup",
    ingredients: ["pumpkin", "onion", "vegetable stock", "cream", "nutmeg"],
    instructions:
      "Cook pumpkin and onion, add stock, blend. Stir in cream and nutmeg.",
    image: "https://example.com/images/pumpkin-soup.jpg",
    tags: ["autumn", "soup", "vegetarian"],
    author: "Hannah Müller",
  },
  {
    id: 18,
    title: "Shrimp Scampi",
    ingredients: [
      "shrimp",
      "garlic",
      "butter",
      "lemon",
      "parsley",
      "spaghetti",
    ],
    instructions:
      "Cook shrimp in garlic butter, add lemon. Toss with pasta and parsley.",
    image: "https://example.com/images/shrimp-scampi.jpg",
    tags: ["seafood", "italian", "dinner"],
    author: "Antonio Bianchi",
  },
  {
    id: 19,
    title: "Miso Soup",
    ingredients: ["miso paste", "tofu", "seaweed", "green onion", "dashi"],
    instructions:
      "Heat dashi, dissolve miso, add tofu and seaweed. Garnish with onion.",
    image: "https://example.com/images/miso-soup.jpg",
    tags: ["japanese", "soup", "healthy"],
    author: "Naoko Sato",
  },
  {
    id: 20,
    title: "BLT Sandwich",
    ingredients: ["bread", "bacon", "lettuce", "tomato", "mayonnaise"],
    instructions: "Toast bread. Layer bacon, lettuce, tomato, spread mayo.",
    image: "https://example.com/images/blt.jpg",
    tags: ["american", "lunch", "quick"],
    author: "Robert Lee",
  },
  {
    id: 21,
    title: "Ratatouille",
    ingredients: [
      "eggplant",
      "zucchini",
      "bell pepper",
      "tomatoes",
      "onion",
      "garlic",
      "thyme",
    ],
    instructions: "Slice and roast veggies. Layer in a dish, bake with herbs.",
    image: "https://example.com/images/ratatouille.jpg",
    tags: ["french", "vegetarian", "summer"],
    author: "Claire Dupont",
  },
  {
    id: 22,
    title: "Pesto Pasta",
    ingredients: [
      "pasta",
      "basil",
      "pine nuts",
      "parmesan",
      "olive oil",
      "garlic",
    ],
    instructions: "Blend pesto ingredients. Cook pasta, toss with pesto.",
    image: "https://example.com/images/pesto-pasta.jpg",
    tags: ["italian", "vegetarian", "quick"],
    author: "Mario Russo",
  },
  {
    id: 23,
    title: "Caesar Salad",
    ingredients: [
      "romaine lettuce",
      "croutons",
      "parmesan",
      "caesar dressing",
      "chicken",
    ],
    instructions:
      "Toss lettuce, chicken, and croutons with dressing. Top with parmesan.",
    image: "https://example.com/images/caesar-salad.jpg",
    tags: ["salad", "classic", "lunch"],
    author: "Julia Roberts",
  },
  {
    id: 24,
    title: "Banana Bread",
    ingredients: ["bananas", "flour", "sugar", "eggs", "butter", "baking soda"],
    instructions: "Mix all ingredients, bake until golden.",
    image: "https://example.com/images/banana-bread.jpg",
    tags: ["baking", "dessert", "sweet"],
    author: "Alex Brown",
  },
  {
    id: 25,
    title: "Tom Yum Soup",
    ingredients: [
      "shrimp",
      "lemongrass",
      "lime",
      "chilies",
      "mushrooms",
      "fish sauce",
    ],
    instructions:
      "Boil broth with spices. Add shrimp and mushrooms. Serve with lime.",
    image: "https://example.com/images/tom-yum.jpg",
    tags: ["thai", "soup", "spicy"],
    author: "Pimchanok Lertsakul",
  },
  {
    id: 26,
    title: "Eggplant Parmesan",
    ingredients: [
      "eggplant",
      "tomato sauce",
      "mozzarella",
      "parmesan",
      "breadcrumbs",
    ],
    instructions: "Bread and fry eggplant. Layer with sauce and cheese. Bake.",
    image: "https://example.com/images/eggplant-parm.jpg",
    tags: ["italian", "bake", "vegetarian"],
    author: "Rosa DeLuca",
  },
  {
    id: 27,
    title: "Goulash",
    ingredients: [
      "beef",
      "onion",
      "paprika",
      "potatoes",
      "carrots",
      "tomato paste",
    ],
    instructions:
      "Brown beef and onions. Add veggies and spices. Simmer until tender.",
    image: "https://example.com/images/goulash.jpg",
    tags: ["hungarian", "stew", "hearty"],
    author: "Janos Kovacs",
  },
  {
    id: 28,
    title: "Mango Lassi",
    ingredients: ["mango", "yogurt", "milk", "honey", "cardamom"],
    instructions: "Blend all ingredients until smooth. Serve chilled.",
    image: "https://example.com/images/mango-lassi.jpg",
    tags: ["indian", "drink", "sweet"],
    author: "Priya Patel",
  },
  {
    id: 29,
    title: "Pho",
    ingredients: [
      "rice noodles",
      "beef",
      "beef broth",
      "bean sprouts",
      "basil",
      "lime",
    ],
    instructions:
      "Simmer broth. Cook noodles, assemble with beef and toppings.",
    image: "https://example.com/images/pho.jpg",
    tags: ["vietnamese", "soup", "noodles"],
    author: "Minh Nguyen",
  },
  {
    id: 30,
    title: "Apple Pie",
    ingredients: [
      "apples",
      "sugar",
      "flour",
      "butter",
      "cinnamon",
      "pie crust",
    ],
    instructions: "Fill crust with apples and sugar. Cover and bake.",
    image: "https://example.com/images/apple-pie.jpg",
    tags: ["dessert", "baking", "classic"],
    author: "Debbie White",
  },
  {
    id: 31,
    title: "Stuffed Bell Peppers",
    ingredients: [
      "bell peppers",
      "ground beef",
      "rice",
      "tomato sauce",
      "cheddar",
    ],
    instructions:
      "Stuff peppers with meat and rice, top with sauce and cheese. Bake.",
    image: "https://example.com/images/stuffed-peppers.jpg",
    tags: ["dinner", "bake", "comfort food"],
    author: "Elena Garcia",
  },
  {
    id: 32,
    title: "Lentil Soup",
    ingredients: ["lentils", "carrots", "celery", "onion", "tomato", "garlic"],
    instructions: "Simmer all ingredients in a pot until lentils are soft.",
    image: "https://example.com/images/lentil-soup.jpg",
    tags: ["vegan", "soup", "healthy"],
    author: "Fatima Abbas",
  },
  {
    id: 33,
    title: "Classic Hummus",
    ingredients: [
      "chickpeas",
      "tahini",
      "lemon",
      "garlic",
      "olive oil",
      "cumin",
    ],
    instructions: "Blend all ingredients until smooth. Drizzle with olive oil.",
    image: "https://example.com/images/hummus.jpg",
    tags: ["middle eastern", "vegan", "dip"],
    author: "Khaled Mansour",
  },
  {
    id: 34,
    title: "Ceviche",
    ingredients: [
      "white fish",
      "lime",
      "onion",
      "cilantro",
      "tomato",
      "avocado",
    ],
    instructions: "Marinate fish in lime, mix with veggies, serve chilled.",
    image: "https://example.com/images/ceviche.jpg",
    tags: ["seafood", "peruvian", "starter"],
    author: "Lucia Reyes",
  },
  {
    id: 35,
    title: "Chocolate Chip Cookies",
    ingredients: [
      "flour",
      "sugar",
      "butter",
      "eggs",
      "chocolate chips",
      "vanilla",
    ],
    instructions: "Mix ingredients, spoon onto tray, bake until golden.",
    image: "https://example.com/images/cookies.jpg",
    tags: ["dessert", "baking", "sweet"],
    author: "Henry Clark",
  },
  {
    id: 36,
    title: "Margherita Pizza",
    ingredients: [
      "pizza dough",
      "tomato sauce",
      "mozzarella",
      "basil",
      "olive oil",
    ],
    instructions:
      "Top dough with sauce, cheese, and basil. Bake until crust is crisp.",
    image: "https://example.com/images/margherita-pizza.jpg",
    tags: ["italian", "pizza", "vegetarian"],
    author: "Giulia Romano",
  },
  {
    id: 37,
    title: "Borscht",
    ingredients: [
      "beetroot",
      "cabbage",
      "carrot",
      "potato",
      "onion",
      "sour cream",
    ],
    instructions: "Cook veggies in broth, blend some, top with sour cream.",
    image: "https://example.com/images/borscht.jpg",
    tags: ["ukrainian", "soup", "vegetarian"],
    author: "Viktor Petrov",
  },
  {
    id: 38,
    title: "Moroccan Couscous",
    ingredients: [
      "couscous",
      "chickpeas",
      "carrot",
      "zucchini",
      "raisins",
      "cinnamon",
    ],
    instructions: "Cook couscous, steam veggies, mix with spices and raisins.",
    image: "https://example.com/images/couscous.jpg",
    tags: ["moroccan", "vegan", "grain"],
    author: "Amina Benali",
  },
  {
    id: 39,
    title: "BBQ Ribs",
    ingredients: ["pork ribs", "bbq sauce", "garlic", "brown sugar", "paprika"],
    instructions: "Season ribs, bake, baste with sauce and grill.",
    image: "https://example.com/images/bbq-ribs.jpg",
    tags: ["american", "grill", "dinner"],
    author: "Jack Wilson",
  },
  {
    id: 40,
    title: "Samosas",
    ingredients: ["potatoes", "peas", "onion", "curry powder", "pastry", "oil"],
    instructions: "Stuff pastry with spiced filling, fold and fry.",
    image: "https://example.com/images/samosas.jpg",
    tags: ["indian", "snack", "vegetarian"],
    author: "Raj Singh",
  },
  {
    id: 41,
    title: "Seafood Paella",
    ingredients: ["rice", "shrimp", "mussels", "saffron", "peas", "tomato"],
    instructions: "Cook rice with saffron and broth, add seafood and veggies.",
    image: "https://example.com/images/paella.jpg",
    tags: ["spanish", "seafood", "rice"],
    author: "Carlos Fernandez",
  },
  {
    id: 42,
    title: "Roast Chicken",
    ingredients: ["chicken", "rosemary", "lemon", "garlic", "olive oil"],
    instructions: "Season chicken, roast with lemon and garlic.",
    image: "https://example.com/images/roast-chicken.jpg",
    tags: ["dinner", "roast", "classic"],
    author: "Elizabeth Harris",
  },
  {
    id: 43,
    title: "Minestrone Soup",
    ingredients: ["beans", "pasta", "carrot", "celery", "tomato", "spinach"],
    instructions: "Simmer all ingredients in broth. Add pasta near end.",
    image: "https://example.com/images/minestrone.jpg",
    tags: ["italian", "soup", "vegetarian"],
    author: "Bella Moretti",
  },
  {
    id: 44,
    title: "Eggs Benedict",
    ingredients: [
      "eggs",
      "english muffin",
      "ham",
      "hollandaise sauce",
      "butter",
    ],
    instructions: "Poach eggs, toast muffins, layer with ham and sauce.",
    image: "https://example.com/images/eggs-benedict.jpg",
    tags: ["breakfast", "brunch", "classic"],
    author: "Lydia Scott",
  },
  {
    id: 45,
    title: "Beef Stroganoff",
    ingredients: ["beef", "mushrooms", "onion", "sour cream", "egg noodles"],
    instructions:
      "Cook beef and mushrooms. Add onions and cook until softened. Stir in sour cream and simmer. Serve hot over egg noodles.",
    image: "https://example.com/images/stroganoff.jpg",
    tags: ["russian", "dinner", "comfort food"],
    author: "Nina Volkov",
  },
  {
    id: 46,
    title: "Chili Con Carne",
    ingredients: [
      "ground beef",
      "kidney beans",
      "tomato",
      "onion",
      "chili powder",
      "garlic",
    ],
    instructions:
      "Brown the beef with onion and garlic. Add tomatoes, beans, and spices. Simmer until thick.",
    image: "https://example.com/images/chili.jpg",
    tags: ["mexican", "spicy", "stew"],
    author: "Derek Riccardo",
  },
  {
    id: 47,
    title: "Tofu Buddha Bowl",
    ingredients: [
      "tofu",
      "quinoa",
      "spinach",
      "carrot",
      "avocado",
      "sesame dressing",
    ],
    instructions:
      "Bake tofu until crispy. Assemble bowl with quinoa, veggies, and dressing.",
    image: "https://example.com/images/buddha-bowl.jpg",
    tags: ["vegan", "healthy", "bowl"],
    author: "Tanya Green",
  },
  {
    id: 48,
    title: "Gnocchi with Pesto",
    ingredients: [
      "gnocchi",
      "basil pesto",
      "parmesan",
      "cherry tomatoes",
      "olive oil",
    ],
    instructions:
      "Boil gnocchi until they float. Toss with pesto and roasted tomatoes. Top with cheese.",
    image: "https://example.com/images/gnocchi-pesto.jpg",
    tags: ["italian", "pasta", "vegetarian"],
    author: "Luca Bellini",
  },
  {
    id: 49,
    title: "Turkey Club Sandwich",
    ingredients: ["turkey", "bacon", "lettuce", "tomato", "mayo", "toast"],
    instructions:
      "Toast bread. Stack turkey, bacon, and veggies with mayo between slices.",
    image: "https://example.com/images/turkey-club.jpg",
    tags: ["american", "lunch", "sandwich"],
    author: "Rachel Brooks",
  },
  {
    id: 50,
    title: "Butter Chicken",
    ingredients: [
      "chicken",
      "butter",
      "tomato sauce",
      "cream",
      "garam masala",
      "ginger",
      "garlic",
    ],
    instructions:
      "Marinate and cook chicken. Simmer sauce with spices and butter. Add chicken and cream, cook until rich.",
    image: "https://example.com/images/butter-chicken.jpg",
    tags: ["indian", "curry", "comfort food"],
    author: "Djubey Mandhavikja",
  },
  {
    id: 51,
    title: "Vegetarian Chili",
    ingredients: [
      "kidney beans",
      "black beans",
      "tomatoes",
      "onion",
      "bell pepper",
      "chili powder",
    ],
    instructions:
      "Sauté vegetables. Add beans, tomatoes, and spices. Simmer until thick.",
    image: "https://example.com/images/vegetarian-chili.jpg",
    tags: ["vegan", "spicy", "stew"],
    author: "Linda Parker",
  },
  {
    id: 52,
    title: "Teriyaki Salmon",
    ingredients: [
      "salmon fillets",
      "soy sauce",
      "honey",
      "garlic",
      "ginger",
      "sesame seeds",
    ],
    instructions:
      "Marinate salmon. Bake or grill until cooked. Sprinkle with sesame seeds.",
    image: "https://example.com/images/teriyaki-salmon.jpg",
    tags: ["japanese", "seafood", "healthy"],
    author: "Akira Yamamoto",
  },
  {
    id: 53,
    title: "Zucchini Bread",
    ingredients: ["zucchini", "flour", "sugar", "eggs", "butter", "cinnamon"],
    instructions: "Mix ingredients, pour into loaf pan, bake until golden.",
    image: "https://example.com/images/zucchini-bread.jpg",
    tags: ["baking", "sweet", "vegetarian"],
    author: "Sara Thompson",
  },
  {
    id: 54,
    title: "Quiche Lorraine",
    ingredients: ["pie crust", "eggs", "cream", "bacon", "gruyere cheese"],
    instructions:
      "Prepare crust, fill with egg mixture, bacon, and cheese. Bake until set.",
    image: "https://example.com/images/quiche-lorraine.jpg",
    tags: ["french", "brunch", "bake"],
    author: "Camille Lefevre",
  },
  {
    id: 55,
    title: "Ramen",
    ingredients: [
      "ramen noodles",
      "broth",
      "egg",
      "pork belly",
      "green onion",
      "nori",
    ],
    instructions: "Prepare broth, cook noodles, assemble with toppings.",
    image: "https://example.com/images/ramen.jpg",
    tags: ["japanese", "soup", "comfort food"],
    author: "Kenji Ito",
  },
  {
    id: 56,
    title: "Tiramisu",
    ingredients: [
      "ladyfingers",
      "mascarpone",
      "espresso",
      "cocoa powder",
      "sugar",
      "eggs",
    ],
    instructions:
      "Layer soaked ladyfingers with mascarpone mixture. Chill and dust with cocoa.",
    image: "https://example.com/images/tiramisu.jpg",
    tags: ["italian", "dessert", "classic"],
    author: "Chiara Conti",
  },
  {
    id: 57,
    title: "Veggie Omelette",
    ingredients: ["eggs", "spinach", "mushrooms", "cheddar", "bell pepper"],
    instructions: "Sauté vegetables. Add beaten eggs, cook, fold with cheese.",
    image: "https://example.com/images/veggie-omelette.jpg",
    tags: ["breakfast", "healthy", "quick"],
    author: "David Collins",
  },
  {
    id: 58,
    title: "Pulled Pork Sandwich",
    ingredients: ["pork shoulder", "bbq sauce", "coleslaw", "burger buns"],
    instructions:
      "Slow cook pork with sauce. Shred and serve in buns with slaw.",
    image: "https://example.com/images/pulled-pork.jpg",
    tags: ["american", "sandwich", "bbq"],
    author: "Tyler Brooks",
  },
  {
    id: 59,
    title: "Gazpacho",
    ingredients: [
      "tomatoes",
      "cucumber",
      "bell pepper",
      "garlic",
      "olive oil",
      "vinegar",
    ],
    instructions: "Blend all ingredients until smooth. Chill before serving.",
    image: "https://example.com/images/gazpacho.jpg",
    tags: ["spanish", "vegan", "cold soup"],
    author: "Isabel Lopez",
  },
  {
    id: 60,
    title: "Stuffed Mushrooms",
    ingredients: [
      "mushrooms",
      "cream cheese",
      "garlic",
      "breadcrumbs",
      "parsley",
    ],
    instructions: "Stuff mushrooms with filling, bake until golden.",
    image: "https://example.com/images/stuffed-mushrooms.jpg",
    tags: ["appetizer", "vegetarian", "bake"],
    author: "Paul Anderson",
  },
  {
    id: 61,
    title: "Chicken Fajitas",
    ingredients: [
      "chicken breast",
      "bell peppers",
      "onion",
      "fajita seasoning",
      "tortillas",
    ],
    instructions:
      "Sauté chicken and vegetables with seasoning. Serve in tortillas.",
    image: "https://example.com/images/chicken-fajitas.jpg",
    tags: ["mexican", "dinner", "quick"],
    author: "Rosa Delgado",
  },
  {
    id: 62,
    title: "Lamb Curry",
    ingredients: [
      "lamb",
      "onion",
      "tomatoes",
      "garam masala",
      "ginger",
      "garlic",
    ],
    instructions: "Cook lamb with spices, simmer in tomato sauce until tender.",
    image: "https://example.com/images/lamb-curry.jpg",
    tags: ["indian", "spicy", "stew"],
    author: "Sanjay Mehta",
  },
  {
    id: 63,
    title: "Fettuccine Alfredo",
    ingredients: ["fettuccine", "butter", "cream", "parmesan"],
    instructions:
      "Cook pasta, toss with sauce made from butter, cream, and cheese.",
    image: "https://example.com/images/fettuccine-alfredo.jpg",
    tags: ["italian", "pasta", "creamy"],
    author: "Marco Bellini",
  },
  {
    id: 64,
    title: "Baklava",
    ingredients: [
      "phyllo pastry",
      "walnuts",
      "pistachios",
      "honey",
      "cinnamon",
      "butter",
    ],
    instructions: "Layer pastry with nuts, bake, and soak with honey syrup.",
    image: "https://example.com/images/baklava.jpg",
    tags: ["middle eastern", "dessert", "sweet"],
    author: "Nadia Hassan",
  },
  {
    id: 65,
    title: "Clam Chowder",
    ingredients: ["clams", "potatoes", "onion", "celery", "cream", "bacon"],
    instructions: "Cook vegetables, add clams and cream. Simmer until thick.",
    image: "https://example.com/images/clam-chowder.jpg",
    tags: ["american", "soup", "seafood"],
    author: "Tom Richards",
  },
  {
    id: 66,
    title: "Pavlova",
    ingredients: [
      "egg whites",
      "sugar",
      "cornstarch",
      "vinegar",
      "whipped cream",
      "berries",
    ],
    instructions: "Bake meringue, top with cream and fruit.",
    image: "https://example.com/images/pavlova.jpg",
    tags: ["australian", "dessert", "sweet"],
    author: "Sophie Bennett",
  },
  {
    id: 67,
    title: "Shepherd's Pie",
    ingredients: ["ground lamb", "onion", "peas", "carrots", "mashed potatoes"],
    instructions: "Cook meat with vegetables, top with mashed potatoes, bake.",
    image: "https://example.com/images/shepherds-pie.jpg",
    tags: ["british", "bake", "comfort food"],
    author: "Oliver Green",
  },
  {
    id: 68,
    title: "Bulgur Salad",
    ingredients: [
      "bulgur",
      "tomato",
      "cucumber",
      "parsley",
      "mint",
      "lemon juice",
    ],
    instructions: "Soak bulgur, mix with chopped vegetables and herbs.",
    image: "https://example.com/images/bulgur-salad.jpg",
    tags: ["vegan", "healthy", "salad"],
    author: "Layla Osman",
  },
  {
    id: 69,
    title: "Lobster Bisque",
    ingredients: ["lobster", "cream", "tomato paste", "onion", "brandy"],
    instructions:
      "Simmer lobster shells for broth, blend with cream and seasoning.",
    image: "https://example.com/images/lobster-bisque.jpg",
    tags: ["french", "seafood", "soup"],
    author: "Jacques Martin",
  },
  {
    id: 70,
    title: "Korean Bibimbap",
    ingredients: ["rice", "beef", "spinach", "carrot", "egg", "gochujang"],
    instructions:
      "Cook vegetables and beef separately, serve over rice with egg and sauce.",
    image: "https://example.com/images/bibimbap.jpg",
    tags: ["korean", "rice", "healthy"],
    author: "Yuna Park",
  },
  {
    id: 71,
    title: "Beet Salad with Goat Cheese",
    ingredients: [
      "beets",
      "goat cheese",
      "walnuts",
      "arugula",
      "balsamic glaze",
    ],
    instructions:
      "Roast beets, slice, and serve with cheese, nuts, and arugula.",
    image: "https://example.com/images/beet-salad.jpg",
    tags: ["salad", "vegetarian", "healthy"],
    author: "Holly Stevens",
  },
  {
    id: 72,
    title: "Prawn Laksa",
    ingredients: [
      "prawns",
      "coconut milk",
      "laksa paste",
      "rice noodles",
      "bean sprouts",
    ],
    instructions:
      "Cook paste in coconut milk, add prawns and noodles. Top with sprouts.",
    image: "https://example.com/images/prawn-laksa.jpg",
    tags: ["malaysian", "spicy", "soup"],
    author: "Amira Zulkifli",
  },
  {
    id: 73,
    title: "Focaccia Bread",
    ingredients: ["flour", "yeast", "olive oil", "rosemary", "salt"],
    instructions:
      "Make dough, let rise, press into pan, top with oil and herbs, bake.",
    image: "https://example.com/images/focaccia.jpg",
    tags: ["italian", "bread", "baking"],
    author: "Giovanni Romano",
  },
  {
    id: 74,
    title: "Shrimp Tempura",
    ingredients: ["shrimp", "tempura batter", "oil", "soy sauce", "ginger"],
    instructions:
      "Dip shrimp in batter, fry until crisp. Serve with dipping sauce.",
    image: "https://example.com/images/shrimp-tempura.jpg",
    tags: ["japanese", "seafood", "fried"],
    author: "Satoshi Mori",
  },
  {
    id: 75,
    title: "Shish Kebab",
    ingredients: ["lamb", "bell pepper", "onion", "tomato", "yogurt marinade"],
    instructions: "Marinate meat, skewer with vegetables, grill.",
    image: "https://example.com/images/shish-kebab.jpg",
    tags: ["middle eastern", "grill", "dinner"],
    author: "Farid Ahmad",
  },
  {
    id: 76,
    title: "Peach Cobbler",
    ingredients: ["peaches", "sugar", "flour", "butter", "baking powder"],
    instructions: "Place peaches in dish, top with batter, bake until golden.",
    image: "https://example.com/images/peach-cobbler.jpg",
    tags: ["dessert", "baking", "sweet"],
    author: "Nancy Williams",
  },
  {
    id: 77,
    title: "Pad See Ew",
    ingredients: ["rice noodles", "soy sauce", "egg", "broccoli", "beef"],
    instructions:
      "Stir-fry beef and broccoli, add noodles and sauce, cook until coated.",
    image: "https://example.com/images/pad-see-ew.jpg",
    tags: ["thai", "noodles", "stir-fry"],
    author: "Chai Sutham",
  },
  {
    id: 78,
    title: "Crème Brûlée",
    ingredients: ["cream", "egg yolks", "sugar", "vanilla"],
    instructions:
      "Bake custard in ramekins, chill, sprinkle sugar, caramelize with torch.",
    image: "https://example.com/images/creme-brulee.jpg",
    tags: ["french", "dessert", "classic"],
    author: "Pierre Laurent",
  },
  {
    id: 79,
    title: "Banh Mi",
    ingredients: [
      "baguette",
      "pork",
      "pickled vegetables",
      "cilantro",
      "mayonnaise",
    ],
    instructions: "Assemble baguette with meat, pickles, herbs, and mayo.",
    image: "https://example.com/images/banh-mi.jpg",
    tags: ["vietnamese", "sandwich", "street food"],
    author: "Thanh Le",
  },
  {
    id: 80,
    title: "Okonomiyaki",
    ingredients: [
      "cabbage",
      "flour",
      "egg",
      "pork belly",
      "okonomiyaki sauce",
      "mayonnaise",
    ],
    instructions:
      "Mix batter with cabbage, cook on griddle, top with sauce and mayo.",
    image: "https://example.com/images/okonomiyaki.jpg",
    tags: ["japanese", "pancake", "savory"],
    author: "Haruka Fujimoto",
  },
  {
    id: 81,
    title: "Spanakopita",
    ingredients: ["phyllo pastry", "spinach", "feta cheese", "onion", "dill"],
    instructions:
      "Layer pastry with spinach and feta filling, bake until golden.",
    image: "https://example.com/images/spanakopita.jpg",
    tags: ["greek", "pie", "vegetarian"],
    author: "Dimitris Papas",
  },
  {
    id: 82,
    title: "Churros",
    ingredients: ["flour", "water", "butter", "sugar", "cinnamon", "oil"],
    instructions: "Make dough, pipe into hot oil, fry, roll in cinnamon sugar.",
    image: "https://example.com/images/churros.jpg",
    tags: ["spanish", "dessert", "fried"],
    author: "Maria Gonzalez",
  },
  {
    id: 83,
    title: "Stuffed Zucchini Boats",
    ingredients: [
      "zucchini",
      "ground turkey",
      "tomato sauce",
      "mozzarella",
      "breadcrumbs",
    ],
    instructions: "Hollow zucchini, fill with mixture, bake until tender.",
    image: "https://example.com/images/zucchini-boats.jpg",
    tags: ["healthy", "bake", "dinner"],
    author: "Emily Carter",
  },
  {
    id: 84,
    title: "French Crepes",
    ingredients: ["flour", "milk", "eggs", "butter", "sugar", "vanilla"],
    instructions:
      "Make thin batter, cook on skillet, fill with sweet or savory fillings.",
    image: "https://example.com/images/crepes.jpg",
    tags: ["french", "breakfast", "dessert"],
    author: "Sophie Lambert",
  },
  {
    id: 85,
    title: "Peking Duck",
    ingredients: ["duck", "hoisin sauce", "scallions", "cucumber", "pancakes"],
    instructions: "Roast duck until crisp, serve with pancakes and toppings.",
    image: "https://example.com/images/peking-duck.jpg",
    tags: ["chinese", "roast", "dinner"],
    author: "Li Wei",
  },
  {
    id: 86,
    title: "Risotto alla Milanese",
    ingredients: [
      "arborio rice",
      "saffron",
      "parmesan",
      "butter",
      "onion",
      "white wine",
    ],
    instructions:
      "Cook onion, add rice and wine, gradually add broth, finish with saffron and cheese.",
    image: "https://example.com/images/risotto.jpg",
    tags: ["italian", "rice", "creamy"],
    author: "Lorenzo Vitale",
  },
  {
    id: 87,
    title: "Hot and Sour Soup",
    ingredients: [
      "tofu",
      "mushrooms",
      "vinegar",
      "soy sauce",
      "egg",
      "chili paste",
    ],
    instructions:
      "Simmer broth with vegetables, add tofu, season with vinegar and chili.",
    image: "https://example.com/images/hot-sour-soup.jpg",
    tags: ["chinese", "soup", "spicy"],
    author: "Mei Zhang",
  },
  {
    id: 88,
    title: "Beef Wellington",
    ingredients: [
      "beef tenderloin",
      "mushrooms",
      "puff pastry",
      "prosciutto",
      "mustard",
    ],
    instructions:
      "Wrap seared beef with mushroom mix and pastry, bake until golden.",
    image: "https://example.com/images/beef-wellington.jpg",
    tags: ["british", "bake", "luxury"],
    author: "Gordon Ellis",
  },
  {
    id: 89,
    title: "Tomato Bruschetta",
    ingredients: ["baguette", "tomatoes", "basil", "garlic", "olive oil"],
    instructions: "Toast bread, top with tomato mix and drizzle with oil.",
    image: "https://example.com/images/bruschetta.jpg",
    tags: ["italian", "appetizer", "vegetarian"],
    author: "Francesca Bianchi",
  },
  {
    id: 90,
    title: "Falooda",
    ingredients: [
      "vermicelli",
      "rose syrup",
      "milk",
      "basil seeds",
      "ice cream",
    ],
    instructions: "Layer ingredients in glass, top with ice cream.",
    image: "https://example.com/images/falooda.jpg",
    tags: ["indian", "drink", "dessert"],
    author: "Ananya Sharma",
  },
  {
    id: 91,
    title: "Chicken Katsu Curry",
    ingredients: ["chicken breast", "panko breadcrumbs", "curry sauce", "rice"],
    instructions: "Bread and fry chicken, serve with curry sauce over rice.",
    image: "https://example.com/images/katsu-curry.jpg",
    tags: ["japanese", "fried", "curry"],
    author: "Takumi Sato",
  },
  {
    id: 92,
    title: "Roasted Vegetable Lasagna",
    ingredients: [
      "lasagna noodles",
      "zucchini",
      "eggplant",
      "tomato sauce",
      "ricotta",
      "mozzarella",
    ],
    instructions:
      "Layer noodles with vegetables, sauce, and cheese. Bake until bubbly.",
    image: "https://example.com/images/veg-lasagna.jpg",
    tags: ["italian", "bake", "vegetarian"],
    author: "Alessia Romano",
  },
  {
    id: 93,
    title: "Kofta Kebabs",
    ingredients: ["ground lamb", "onion", "garlic", "parsley", "spices"],
    instructions: "Shape meat mixture onto skewers, grill until cooked.",
    image: "https://example.com/images/kofta.jpg",
    tags: ["middle eastern", "grill", "spicy"],
    author: "Omar Farouk",
  },
  {
    id: 94,
    title: "Egg Curry",
    ingredients: [
      "boiled eggs",
      "onion",
      "tomatoes",
      "curry powder",
      "garlic",
      "ginger",
    ],
    instructions: "Cook sauce with spices, add eggs, simmer gently.",
    image: "https://example.com/images/egg-curry.jpg",
    tags: ["indian", "spicy", "vegetarian"],
    author: "Ravi Kapoor",
  },
  {
    id: 95,
    title: "Carrot Cake",
    ingredients: [
      "carrots",
      "flour",
      "sugar",
      "eggs",
      "butter",
      "cream cheese frosting",
    ],
    instructions: "Mix ingredients, bake, and frost when cool.",
    image: "https://example.com/images/carrot-cake.jpg",
    tags: ["dessert", "baking", "sweet"],
    author: "Linda Morris",
  },
  {
    id: 96,
    title: "Jollof Rice",
    ingredients: [
      "rice",
      "tomatoes",
      "onion",
      "bell pepper",
      "spices",
      "chicken",
    ],
    instructions: "Cook rice in spiced tomato sauce with meat or vegetables.",
    image: "https://example.com/images/jollof-rice.jpg",
    tags: ["african", "rice", "spicy"],
    author: "Adebola Adebayo",
  },
  {
    id: 97,
    title: "Chow Mein",
    ingredients: [
      "egg noodles",
      "chicken",
      "soy sauce",
      "bean sprouts",
      "carrot",
      "cabbage",
    ],
    instructions:
      "Stir-fry noodles with vegetables and meat, season with soy sauce.",
    image: "https://example.com/images/chow-mein.jpg",
    tags: ["chinese", "noodles", "stir-fry"],
    author: "Hao Chen",
  },
  {
    id: 98,
    title: "Key Lime Pie",
    ingredients: [
      "key lime juice",
      "sweetened condensed milk",
      "egg yolks",
      "graham cracker crust",
    ],
    instructions: "Mix filling, pour into crust, bake, and chill.",
    image: "https://example.com/images/key-lime-pie.jpg",
    tags: ["dessert", "baking", "sweet"],
    author: "Barbara White",
  },
  {
    id: 99,
    title: "Moussaka",
    ingredients: [
      "eggplant",
      "ground beef",
      "tomatoes",
      "béchamel sauce",
      "cheese",
    ],
    instructions:
      "Layer eggplant with meat sauce and béchamel, bake until golden.",
    image: "https://example.com/images/moussaka.jpg",
    tags: ["greek", "bake", "dinner"],
    author: "Katerina Nikos",
  },
  {
    id: 100,
    title: "Pineapple Fried Rice",
    ingredients: [
      "rice",
      "pineapple",
      "shrimp",
      "cashews",
      "soy sauce",
      "green onions",
    ],
    instructions:
      "Stir-fry rice with pineapple, shrimp, and seasonings. Top with cashews.",
    image: "https://example.com/images/pineapple-fried-rice.jpg",
    tags: ["thai", "rice", "sweet-savory"],
    author: "Somsak Arun",
  },
];

export { recipes };
